# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.


Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.synced_folder "./share", "/vagrant", create: true, disabled: false
  
  # controller
  config.vm.define "nledentS" do |server|
    server.vm.hostname = "nledentS"
    server.vm.network "private_network", ip: "192.168.56.110", interface: "eth1"

    server.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.cpus = 1
      vb.memory = "1024"
      vb.name = "nledentS"
    end
    server.vm.provision "shell", path: "server.sh"
    server.vm.provision "file", source: "./config/app1.yaml", destination: "/config/app1.yaml"
    server.vm.provision "file", source: "./config/app2.yaml", destination: "/config/app2.yaml"
    server.vm.provision "file", source: "./config/app3.yaml", destination: "/config/app3.yaml"
  end

end
