# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.


Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.synced_folder "./config", "/config", create: true, disabled: false
  config.vm.network "forwarded_port", guest: 22, host: 2240

  # controller
  config.vm.define "nledentS" do |server|
    server.vm.hostname = "nledentS"
    server.vm.network "private_network", ip: "192.168.56.110", interface: "eth1"

    server.vm.provider "virtuvagranalbox" do |vb|
      vb.gui = false
      vb.cpus = 1
      vb.memory = "2048"
      vb.name = "nledentS"
    end

    # server.vm.provision "file", source: "./config/app3.yaml", destination: "/config/app3.yaml"
    server.vm.provision "shell", path: "scripts/server.sh"
  end

end
