# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.


Vagrant.configure("2") do |config|

  # controller
  config.vm.define "nledentS" do |server|
    server.vm.box = "debian/buster64"
    server.vm.hostname = "nledentS"
    server.vm.box_version = "10.20231211.1"
    server.vm.network "private_network", ip: "192.168.56.110", interface: "eth1"
    server.vm.synced_folder "./sync", "/vagrant", create: true, disabled: false, type: "rsync"
    server.vm.box_check_update = false

    server.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.cpus = 1
      vb.memory = "1024"
      vb.name = "nledentS"
    end
    server.vm.provision "shell", path: "server.sh"
  end

  # agent
  config.vm.define "bcarolleSW" do |agent|
    agent.vm.box = "debian/buster64"
    agent.vm.hostname = "bcarolleSW"
    agent.vm.box_version = "10.20231211.1"
    agent.vm.network "private_network", ip: "192.168.56.111", interface: "eth1"
    agent.vm.synced_folder "./sync", "/vagrant", create: true, disabled: false, type: "rsync"
    agent.vm.box_check_update = false
    agent.vm.provider "virtualbox" do |vb|
    #   # Display the VirtualBox GUI when booting the machine
      vb.gui = false
      vb.cpus = 1
      vb.memory = "1024"
      vb.name = "bcarolleSW"

    end
    agent.vm.provision "shell", path: "agent.sh"
  end
end